### ISSUE TITLE
Should Return 401 (Unauthorized)

### ISSUE THREAD

**Issue by AlexJuca** [JosefaMonteiro28/AuthenticationJWT#1]
If your client providers correct data in it's request during an authentication request but fails to authenticate due to wrong credentials than returning BadRequest( HTTP status 400) to the client would not be appropriate.

https://github.com/JosefaMonteiro28/AuthenticationJWT/blob/3e76039860db2f3b30a226f7bc6cb6e6442b2c12/AuthenticationJWT.API/Controllers/UsersController.cs#L51

Returning 401 to imply that the authentication failed would be the appropriate HTTP status code to return to the client.

**Comment by JosefaMonteiro28** [comment]
Done
